CREATE TABLE user_account
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255) UNIQUE,
    password  VARCHAR(255)                            NOT NULL,
    ban       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_user_account PRIMARY KEY (id)
);

CREATE TABLE game
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nb_available_shard_tokens INTEGER,
    state VARCHAR(10),
    url VARCHAR(50),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE player
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    game_id BIGINT,
    user_id BIGINT,
    color VARCHAR(255),
    role VARCHAR(255),
    nb_red_flag INTEGER,
    nb_black_flag INTEGER,
    CONSTRAINT pk_player PRIMARY KEY (id),
    FOREIGN KEY(game_id) REFERENCES game(id),
    FOREIGN KEY(user_id) REFERENCES user_account(id)
);

CREATE TABLE token
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id BIGINT,
    owner_id BIGINT,
    type VARCHAR(255),
    CONSTRAINT pk_token PRIMARY KEY (id),
    FOREIGN KEY(owner_id) REFERENCES player(id),
    FOREIGN KEY(player_id) REFERENCES player(id)
);