spring:
  application:
    name: back
  datasource:
    password: ${POSTGRESQL_ADDON_PASSWORD}
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${POSTGRESQL_ADDON_USER}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
