FROM openjdk:21-slim
RUN apt-get update && apt-get install -y curl && apt-get clean autoclean
VOLUME /back
COPY target/back-[0-9]*.[0-9]*.[0-9]*.jar app.jar
EXPOSE 8080
CMD ["java","-jar", "/app.jar", "-Dspring.profiles.active=prod"]