name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-front: 
    name: Build front
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: actions/checkout@v4
    - name: toto
      working-directory: ./front
      run: |
        npm install
        npm run build

  build-docker-image-fo:
    name: Build image FO
    runs-on: ubuntu-latest
    needs: build-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}





      
