name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

defaults: 
  run:
    working-directory: ./front

jobs:
  build-front: 
    name: Build front
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: actions/checkout@v4
    - name: toto
      run: |
        npm install
        npm run build
        docker build -f Dockerfile -t arcuredev/insurrection-front:latest -t arcuredev/insurrection-front:${{github.sha}} .






      
